# Generated by Django 3.2.6 on 2021-08-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event'),
        ),
    ]
