# Generated by Django 3.2.6 on 2021-08-06 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210805_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_link',
            field=models.URLField(blank=True),
        ),
    ]
