# Generated by Django 3.2.6 on 2021-08-06 19:30

from django.db import migrations, models
import sound_frequencies.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210806_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
