# Generated by Django 3.2.6 on 2021-08-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='video',
            name='event',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mix',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
