# Generated by Django 3.2.6 on 2021-08-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210807_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='image',
        ),
    ]
