# Generated by Django 3.2.6 on 2021-08-08 15:53

from django.db import migrations, models
import sound_frequencies.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_photo_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default=sound_frequencies.web.models.generate_image_name, max_length=50),
        ),
    ]
