# Generated by Django 3.2.6 on 2021-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='myphoto.jpg', max_length=50),
        ),
    ]
