# Generated by Django 3.2.6 on 2021-10-17 16:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20211017_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
